### ISSUE TITLE
Employees' flexibility graph

### ISSUE THREAD

**Issue by fleissigal** [shiftlyapp/Shiftly#23]

**Comment by maaudrana** [comment]
@fleissigal Hello dear playstore link is broken can you chack the lin pls?

**Comment by fleissigal** [comment]
@maaudrana Hello and thank you for your interest in Shiftly! We are working on fixing the problem. Expect to see the link fixed within the next two weeks or so

**Comment by maaudrana** [comment]
ok waiting for that

**Comment by fleissigal** [comment]
Done

**Comment by fleissigal** [comment]
@maaudrana Hello again! The app is back in the store, you are welcome to check it out and give us feedback. Thanks!

**Comment by maaudrana** [comment]
@fleissigal but dear i can not download  the app.its not available  in our country

**Comment by fleissigal** [comment]
@maaudrana Hello, I added your country. According to Google updates like that usually become available within a few hours

**Comment by maaudrana** [comment]
Not  yet added.I am from Bangladesh. Its not available  here

**Comment by maaudrana** [comment]
![Screenshot_20190517-212220_Google Play Store](https://user-images.githubusercontent.com/34313493/57938428-fda9fd80-78e9-11e9-8b9d-0d2cfd8afb5c.jpg)

**Comment by fleissigal** [comment]
Please check again in a few hours, it should be available

**Comment by maaudrana** [comment]
Ok tnx
